In [ ]:
%%bash
pip install -q ydata-profiling

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 12.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 19.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 65.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 32.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 4.1 MB/s eta 0:00:00

# Proyecto Final - Minería de Datos
## Fase de Preparación de Datos (Metodología CRISP-DM)
**Dataset:** Credit Card Churn  
**Objetivo:** Realizar la limpieza y preparación inicial de los datos siguiendo los pasos vistos en clase (análisis exploratorio, pandas profiling, tratamiento de nulos con la regla del 15%, detección de atípicos y análisis de correlaciones), sin aplicar todavía balanceo ni transformaciones avanzadas, las cuales se trabajarán en el notebook de modelado.

### 1. Importación de librerías y carga de datos
Cargamos las librerías básicas para manipulación y visualización de datos, y leemos el archivo csv original.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Estilo visual básico
sns.set_style('whitegrid')

# Cargamos el archivo csv
df = pd.read_csv('credit_card_churn.csv')
print(f"Dimensiones iniciales: {df.shape[0]} filas y {df.shape[1]} columnas")
df.head()

Dimensiones iniciales: 10127 filas y 23 columnas

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

### 2. Pandas Profiling
Generamos el reporte con `ydata-profiling` para tener un resumen automatizado del dataset y lo guardamos en un archivo html para anexarlo a la entrega.

In [2]:
from ydata_profiling import ProfileReport

# Excluimos las 2 columnas residuales del final para el reporte
cols_nb = [c for c in df.columns if 'Naive_Bayes' in c]
profile = ProfileReport(df.drop(columns=cols_nb), title="Reporte Profiling - Credit Card Churn", minimal=True)
profile.to_file("reporte_profiling_churn.html")
print("Reporte de Pandas Profiling guardado exitosamente como 'reporte_profiling_churn.html'")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Summarize dataset:   0%|          | 0/26 [00:00<?, ?it/s, Describe variable: CLIENTNUM]

Summarize dataset:   0%|          | 0/26 [00:00<?, ?it/s, Describe variable: Attrition_Flag]

Summarize dataset:   0%|          | 0/26 [00:00<?, ?it/s, Describe variable: Gender]

Summarize dataset:   0%|          | 0/26 [00:00<?, ?it/s, Describe variable: Marital_Status]

Summarize dataset:   0%|          | 0/26 [00:00<?, ?it/s, Describe variable: Income_Category]

Summarize dataset:   0%|          | 0/26 [00:00<?, ?it/s, Describe variable: Total_Relationship_Count]

Summarize dataset:   4%|▍         | 1/26 [00:00<00:01, 13.04it/s, Describe variable: Contacts_Count_12_mon]

Summarize dataset:   8%|▊         | 2/26 [00:00<00:01, 21.86it/s, Describe variable: Credit_Limit]

Summarize dataset:  15%|█▌        | 4/26 [00:00<00:00, 34.49it/s, Describe variable: Credit_Limit]

Summarize dataset:  15%|█▌        | 4/26 [00:00<00:00, 34.49it/s, Describe variable: Credit_Limit]

Summarize dataset:  15%|█▌        | 4/26 [00:00<00:00, 34.49it/s, Describe variable: Credit_Limit]

Summarize dataset:  19%|█▉        | 5/26 [00:00<00:00, 34.28it/s, Describe variable: Credit_Limit]

Summarize dataset:  19%|█▉        | 5/26 [00:00<00:00, 34.28it/s, Describe variable: Credit_Limit]

Summarize dataset:  23%|██▎       | 6/26 [00:00<00:00, 35.93it/s, Describe variable: Credit_Limit]

Summarize dataset:  23%|██▎       | 6/26 [00:00<00:00, 35.93it/s, Describe variable: Credit_Limit]

Summarize dataset:  38%|███▊      | 10/26 [00:00<00:00, 49.86it/s, Describe variable: Total_Revolving_Bal]

Summarize dataset:  42%|████▏     | 11/26 [00:00<00:00, 49.86it/s, Describe variable: Total_Amt_Chng_Q4_Q1]

Summarize dataset:  46%|████▌     | 12/26 [00:00<00:00, 49.86it/s, Describe variable: Total_Trans_Ct]

Summarize dataset:  46%|████▌     | 12/26 [00:00<00:00, 49.86it/s, Describe variable: Total_Ct_Chng_Q4_Q1]

Summarize dataset:  46%|████▌     | 12/26 [00:00<00:00, 49.86it/s, Describe variable: Avg_Utilization_Ratio]

Summarize dataset:  50%|█████     | 13/26 [00:00<00:00, 49.86it/s, Describe variable: Avg_Utilization_Ratio]

Summarize dataset:  50%|█████     | 13/26 [00:00<00:00, 49.86it/s, Describe variable: Avg_Utilization_Ratio]

Summarize dataset:  50%|█████     | 13/26 [00:00<00:00, 49.86it/s, Describe variable: Avg_Utilization_Ratio]

Summarize dataset:  50%|█████     | 13/26 [00:00<00:00, 49.86it/s, Describe variable: Avg_Utilization_Ratio]

Summarize dataset:  50%|█████     | 13/26 [00:00<00:00, 49.86it/s, Describe variable: Avg_Utilization_Ratio]

Summarize dataset:  54%|█████▍    | 14/26 [00:00<00:00, 49.86it/s, Describe variable: Avg_Utilization_Ratio]

Summarize dataset:  54%|█████▍    | 14/26 [00:00<00:00, 49.86it/s, Describe variable: Avg_Utilization_Ratio]

Summarize dataset:  54%|█████▍    | 14/26 [00:00<00:00, 49.86it/s, Describe variable: Avg_Utilization_Ratio]

Summarize dataset:  54%|█████▍    | 14/26 [00:00<00:00, 49.86it/s, Describe variable: Avg_Utilization_Ratio]

  0%|          | 0/21 [00:00<?, ?it/s]

100%|██████████| 21/21 [00:00<00:00, 2979.61it/s]

Summarize dataset:  81%|████████  | 21/26 [00:00<00:00, 49.86it/s, Get variable types]

Summarize dataset:  81%|████████▏ | 22/27 [00:00<00:00, 49.86it/s, Get dataframe statistics]

Summarize dataset:  85%|████████▌ | 23/27 [00:00<00:00, 49.86it/s, Get scatter matrix]

Summarize dataset:  85%|████████▌ | 23/27 [00:00<00:00, 49.86it/s, Take sample]

Summarize dataset:  89%|████████▉ | 24/27 [00:00<00:00, 49.86it/s, Detecting duplicates]

Summarize dataset:  93%|█████████▎| 25/27 [00:00<00:00, 49.86it/s, Get alerts]

Summarize dataset:  96%|█████████▋| 26/27 [00:00<00:00, 49.86it/s, Get reproduction details]

Summarize dataset: 100%|██████████| 27/27 [00:00<00:00, 69.42it/s, Get reproduction details]

Summarize dataset: 100%|██████████| 27/27 [00:00<00:00, 69.42it/s, Completed]

Summarize dataset: 100%|██████████| 27/27 [00:00<00:00, 98.10it/s, Completed]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Generate report structure: 100%|██████████| 1/1 [00:05<00:00,  5.58s/it]

Generate report structure: 100%|██████████| 1/1 [00:05<00:00,  5.58s/it]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s]

Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file: 100%|██████████| 1/1 [00:00<00:00, 56.95it/s]

Reporte de Pandas Profiling guardado exitosamente como 'reporte_profiling_churn.html'

### 3. Selección inicial de variables (Eliminación de columnas no útiles)
Revisando el dataset y el diccionario encontramos 3 columnas que debemos quitar desde el inicio:
- Cliente : Es solo el ID del cliente, no tiene valor predictivo.
- Las dos columnas finales de `Naive_Bayes_Classifier

In [3]:
# Eliminamos el ID y las columnas con fuga de datos
cols_eliminar = [
    'CLIENTNUM',
    'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
    'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'
]

df_limpio = df.drop(columns=cols_eliminar).copy()
print(f"Nuevo tamaño del dataset: {df_limpio.shape[0]} filas y {df_limpio.shape[1]} columnas")
print(f"Filas duplicadas: {df_limpio.duplicated().sum()}")

Nuevo tamaño del dataset: 10127 filas y 20 columnas
Filas duplicadas: 0

### 4. Revisión de la variable objetivo (`Attrition_Flag`)

In [4]:
# Conteo de la variable objetivo
print(df_limpio['Attrition_Flag'].value_counts(normalize=True) * 100)

plt.figure(figsize=(6, 4))
sns.countplot(data=df_limpio, x='Attrition_Flag', palette=['#1f77b4', '#ff7f0e'])
plt.title("Distribución de Clientes (Attrition_Flag)", fontweight='bold')
plt.xlabel("Estado del Cliente")
plt.ylabel("Cantidad")
plt.show()

Attrition_Flag
Existing Customer    83.934038
Attrited Customer    16.065962
Name: proportion, dtype: float64

### 5. Reglas de calidad y atípicos (Tabla 4 del informe)
Al inspeccionar las variables categóricas, encontramos que `Education_Level`, `Marital_Status` e `Income_Category` tienen registros con el texto `'Unknown'`.
En el negocio esto no es una categoría real, sino un dato faltante que el banco no capturó. Por lo tanto, los convertimos a `NaN` para poder aplicarles la regla de limpieza de nulos.

En cuanto a las numéricas, revisamos mínimos y máximos para comprobar que no hayan edades negativas ni porcentajes mayores a 1.

In [5]:
# Revisión de rangos de variables numéricas
print(df_limpio.describe().T[['min', 'mean', 'max']].round(2))

# Reemplazamos los 'Unknown' por NaN para tratarlos como valores nulos
df_nulos = df_limpio.replace('Unknown', np.nan)

                             min     mean       max
Customer_Age                26.0    46.33     73.00
Dependent_count              0.0     2.35      5.00
Months_on_book              13.0    35.93     56.00
Total_Relationship_Count     1.0     3.81      6.00
Months_Inactive_12_mon       0.0     2.34      6.00
Contacts_Count_12_mon        0.0     2.46      6.00
Credit_Limit              1438.3  8631.95  34516.00
Total_Revolving_Bal          0.0  1162.81   2517.00
Avg_Open_To_Buy              3.0  7469.14  34516.00
Total_Amt_Chng_Q4_Q1         0.0     0.76      3.40
Total_Trans_Amt            510.0  4404.09  18484.00
Total_Trans_Ct              10.0    64.86    139.00
Total_Ct_Chng_Q4_Q1          0.0     0.71      3.71
Avg_Utilization_Ratio        0.0     0.27      1.00

In [6]:
# Tabla de reglas de calidad de negocio por variable
# Cada regla devuelve una máscara con los registros que la incumplen
d = df_limpio
reglas = {
    'Attrition_Flag': ("Categorías válidas: Existing Customer, Attrited Customer",
                       ~d['Attrition_Flag'].isin(['Existing Customer', 'Attrited Customer'])),
    'Customer_Age': ("Edad entre 18 y 100 años", ~d['Customer_Age'].between(18, 100)),
    'Gender': ("Categorías válidas: M, F", ~d['Gender'].isin(['M', 'F'])),
    'Dependent_count': ("Entero entre 0 y 10", ~d['Dependent_count'].between(0, 10)),
    'Education_Level': ("Categorías válidas: Uneducated, High School, College, Graduate, Post-Graduate, Doctorate",
                        ~d['Education_Level'].isin(['Uneducated', 'High School', 'College', 'Graduate', 'Post-Graduate', 'Doctorate'])),
    'Marital_Status': ("Categorías válidas: Married, Single, Divorced",
                       ~d['Marital_Status'].isin(['Married', 'Single', 'Divorced'])),
    'Income_Category': ("Categorías válidas: Less than $40K, $40K - $60K, $60K - $80K, $80K - $120K, $120K +",
                        ~d['Income_Category'].isin(['Less than $40K', '$40K - $60K', '$60K - $80K', '$80K - $120K', '$120K +'])),
    'Card_Category': ("Categorías válidas: Blue, Silver, Gold, Platinum",
                      ~d['Card_Category'].isin(['Blue', 'Silver', 'Gold', 'Platinum'])),
    'Months_on_book': ("Mayor que 0 y no mayor a (edad - 18) x 12 meses",
                       (d['Months_on_book'] <= 0) | (d['Months_on_book'] > (d['Customer_Age'] - 18) * 12)),
    'Total_Relationship_Count': ("Entero mayor o igual a 1 (al menos la tarjeta)", d['Total_Relationship_Count'] < 1),
    'Months_Inactive_12_mon': ("Entre 0 y 12 meses", ~d['Months_Inactive_12_mon'].between(0, 12)),
    'Contacts_Count_12_mon': ("Conteo no negativo", d['Contacts_Count_12_mon'] < 0),
    'Credit_Limit': ("Mayor que 0", d['Credit_Limit'] <= 0),
    'Total_Revolving_Bal': ("Entre 0 y Credit_Limit",
                            (d['Total_Revolving_Bal'] < 0) | (d['Total_Revolving_Bal'] > d['Credit_Limit'])),
    'Avg_Open_To_Buy': ("No negativo e igual a Credit_Limit - Total_Revolving_Bal (tolerancia 1)",
                        (d['Avg_Open_To_Buy'] < 0) | ((d['Avg_Open_To_Buy'] - (d['Credit_Limit'] - d['Total_Revolving_Bal'])).abs() > 1)),
    'Total_Amt_Chng_Q4_Q1': ("Razón no negativa", d['Total_Amt_Chng_Q4_Q1'] < 0),
    'Total_Trans_Amt': ("Monto no negativo", d['Total_Trans_Amt'] < 0),
    'Total_Trans_Ct': ("Conteo no negativo", d['Total_Trans_Ct'] < 0),
    'Total_Ct_Chng_Q4_Q1': ("Razón no negativa", d['Total_Ct_Chng_Q4_Q1'] < 0),
    'Avg_Utilization_Ratio': ("Entre 0 y 1 e igual a Total_Revolving_Bal / Credit_Limit (tolerancia 0.001)",
                              ~d['Avg_Utilization_Ratio'].between(0, 1) |
                              ((d['Avg_Utilization_Ratio'] - d['Total_Revolving_Bal'] / d['Credit_Limit']).abs() > 0.001)),
}

filas = []
for col, (regla, incumple) in reglas.items():
    if pd.api.types.is_numeric_dtype(d[col]):
        minimo, maximo = d[col].min(), d[col].max()
    else:
        minimo, maximo = ', '.join(sorted(d[col].unique())), '-'
    n = int(incumple.sum())
    filas.append({'Variable': col, 'Regla de calidad': regla,
                  'Mínimo / categorías encontradas': minimo, 'Máximo': maximo,
                  'Registros que incumplen': n, 'Indicio de error': 'Sí' if n > 0 else 'No'})

tabla_calidad = pd.DataFrame(filas)
pd.set_option('display.max_colwidth', None)
tabla_calidad

,Variable,Regla de calidad,Mínimo / categorías encontradas,Máximo,Registros que incumplen,Indicio de error
0,Attrition_Flag,"Categorías válidas: Existing Customer, Attrited Customer","Attrited Customer, Existing Customer",-,0,No
1,Customer_Age,Edad entre 18 y 100 años,26,73,0,No
2,Gender,"Categorías válidas: M, F","F, M",-,0,No
3,Dependent_count,Entero entre 0 y 10,0,5,0,No
4,Education_Level,"Categorías válidas: Uneducated, High School, College, Graduate, Post-Graduate, Doctorate","College, Doctorate, Graduate, High School, Post-Graduate, Uneducated, Unknown",-,1519,Sí
5,Marital_Status,"Categorías válidas: Married, Single, Divorced","Divorced, Married, Single, Unknown",-,749,Sí
6,Income_Category,"Categorías válidas: Less than $40K, $40K - $60K, $60K - $80K, $80K - $120K, $120K +","$120K +, $40K - $60K, $60K - $80K, $80K - $120K, Less than $40K, Unknown",-,1112,Sí
7,Card_Category,"Categorías válidas: Blue, Silver, Gold, Platinum","Blue, Gold, Platinum, Silver",-,0,No
8,Months_on_book,Mayor que 0 y no mayor a (edad - 18) x 12 meses,13,56,0,No
9,Total_Relationship_Count,Entero mayor o igual a 1 (al menos la tarjeta),1,6,0,No
10,Months_Inactive_12_mon,Entre 0 y 12 meses,0,6,0,No
11,Contacts_Count_12_mon,Conteo no negativo,0,6,0,No
12,Credit_Limit,Mayor que 0,1438.3,34516.0,0,No
13,Total_Revolving_Bal,Entre 0 y Credit_Limit,0,2517,0,No
14,Avg_Open_To_Buy,No negativo e igual a Credit_Limit - Total_Revolving_Bal (tolerancia 1),3.0,34516.0,0,No
15,Total_Amt_Chng_Q4_Q1,Razón no negativa,0.0,3.397,0,No
16,Total_Trans_Amt,Monto no negativo,510,18484,0,No
17,Total_Trans_Ct,Conteo no negativo,10,139,0,No
18,Total_Ct_Chng_Q4_Q1,Razón no negativa,0.0,3.714,0,No
19,Avg_Utilization_Ratio,Entre 0 y 1 e igual a Total_Revolving_Bal / Credit_Limit (tolerancia 0.001),0.0,0.999,0,No

In [7]:
# Detección de atípicos con el criterio IQR (1.5 veces el rango intercuartílico)
num_cols = df_limpio.select_dtypes(include=[np.number]).columns
filas_iqr = []
for col in num_cols:
    q1, q3 = df_limpio[col].quantile([0.25, 0.75])
    iqr = q3 - q1
    lim_inf, lim_sup = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    n_atip = ((df_limpio[col] < lim_inf) | (df_limpio[col] > lim_sup)).sum()
    filas_iqr.append({'Variable': col, 'Q1': q1, 'Q3': q3, 'IQR': iqr,
                      'Límite inferior': lim_inf, 'Límite superior': lim_sup,
                      'Atípicos': n_atip, '% atípicos': round(n_atip / len(df_limpio) * 100, 2)})

tabla_iqr = pd.DataFrame(filas_iqr).sort_values('% atípicos', ascending=False).reset_index(drop=True)
print(f"Clientes con Credit_Limit en el tope de 34516: {(df_limpio['Credit_Limit'] == 34516).sum()}")
display(tabla_iqr.round(3))

# Boxplots de las variables numéricas
fig, axes = plt.subplots(4, 4, figsize=(16, 14))
for ax, col in zip(axes.flat, num_cols):
    sns.boxplot(y=df_limpio[col], ax=ax, color='#1f77b4')
    ax.set_title(col, fontsize=10, fontweight='bold')
    ax.set_ylabel('')
for ax in axes.flat[len(num_cols):]:
    ax.set_visible(False)
plt.suptitle("Boxplots de variables numéricas (detección de atípicos con IQR)", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

Clientes con Credit_Limit en el tope de 34516: 508

,Variable,Q1,Q3,IQR,Límite inferior,Límite superior,Atípicos,% atípicos
0,Credit_Limit,2555.000,11067.500,8512.500,-10213.750,23836.250,984,9.72
1,Avg_Open_To_Buy,1324.500,9859.000,8534.500,-11477.250,22660.750,963,9.51
2,Total_Trans_Amt,2155.500,4741.000,2585.500,-1722.750,8619.250,896,8.85
3,Contacts_Count_12_mon,2.000,3.000,1.000,0.500,4.500,629,6.21
4,Total_Amt_Chng_Q4_Q1,0.631,0.859,0.228,0.289,1.201,396,3.91
5,Total_Ct_Chng_Q4_Q1,0.582,0.818,0.236,0.228,1.172,394,3.89
6,Months_on_book,31.000,40.000,9.000,17.500,53.500,386,3.81
7,Months_Inactive_12_mon,2.000,3.000,1.000,0.500,4.500,331,3.27
8,Customer_Age,41.000,52.000,11.000,24.500,68.500,2,0.02
9,Total_Trans_Ct,45.000,81.000,36.000,-9.000,135.000,2,0.02
10,Total_Relationship_Count,3.000,5.000,2.000,0.000,8.000,0,0.00
11,Dependent_count,1.000,3.000,2.000,-2.000,6.000,0,0.00
12,Total_Revolving_Bal,359.000,1784.000,1425.000,-1778.500,3921.500,0,0.00
13,Avg_Utilization_Ratio,0.023,0.503,0.480,-0.697,1.223,0,0.00

#### Decisión sobre reglas de calidad y atípicos
La tabla de reglas de calidad muestra que ninguna variable numérica incumple su regla de negocio. No hay edades por fuera de 18 a 100 años, los conteos y montos son no negativos, la antigüedad nunca supera los meses posibles según la edad, el saldo rotativo nunca excede el cupo, el cupo disponible coincide con el cupo menos el saldo y la razón de utilización está entre 0 y 1 y coincide con el saldo dividido por el cupo. Las únicas variables con indicio de error son `Education_Level`, `Marital_Status` e `Income_Category` por la categoría `Unknown`, que no es un valor real sino un dato que el banco no registró, y por eso la convertimos a `NaN` y la tratamos en la sección de nulos.

Con el criterio del rango intercuartílico los mayores porcentajes de atípicos están en `Credit_Limit` con 984 registros (9.72%), `Avg_Open_To_Buy` con 963 (9.51%), `Total_Trans_Amt` con 896 (8.85%) y `Contacts_Count_12_mon` con 629 (6.21%). Les siguen `Total_Amt_Chng_Q4_Q1`, `Total_Ct_Chng_Q4_Q1`, `Months_on_book` y `Months_Inactive_12_mon` con porcentajes entre 3% y 4%, mientras que `Customer_Age` y `Total_Trans_Ct` tienen solo 2 registros cada una y las demás variables no tienen ninguno.

Proponemos conservar todos estos registros porque son valores legítimos del negocio y no errores de captura. En `Credit_Limit` hay 508 clientes exactamente en 34516, que es el tope de cupo que maneja el banco, y los cupos altos se concentran en clientes con ingresos de 80K o más (74% de los atípicos) y en casi todas las tarjetas Gold y Platinum. Los montos altos de `Total_Trans_Amt` pertenecen a los clientes más activos, cuya tasa de abandono es 9.8% frente al 16.1% general, así que eliminarlos quitaría justamente información que ayuda a separar las clases. Los conteos de contactos, de inactividad y de antigüedad son enteros acotados y el IQR los marca solo porque su distribución está muy concentrada, en el caso de `Months_on_book` con 2463 clientes en 36 meses. Además, borrar filas reduciría todavía más la clase minoritaria. Por estas razones no se elimina ninguna fila en esta etapa, y la diferencia de escalas se controla más adelante con el escalado dentro del Pipeline de modelado.

### 6. Limpieza de valores nulos (Regla del 15% - Tabla 5)
Aplicamos los tres pasos que pide la plantilla del informe:
1. **Eliminar filas con más del 15% de nulos:**  
   En nuestras 19 variables predictoras, si una fila tiene 3 valores faltantes tiene $3/19 = 15.79\% > 15\%$. Se encontraron 7 filas con esta condición y las eliminamos.
2. **Eliminar columnas con más del 15% de nulos:**  
   `Education_Level` aparece con 15.00% en la tabla, pero ese valor sale del redondeo a dos decimales. En realidad tiene 1519 nulos sobre 10127 registros, es decir $1519/10127 = 14.9995\%$, que queda por debajo del 15% y por eso la columna se conserva y se imputa en vez de eliminarse (el cálculo exacto se muestra en la celda que sigue a la limpieza). `Income_Category` tiene 10.98% y `Marital_Status` tiene 7.40%. Ninguna supera el 15%, por lo que no se borra ninguna columna.
3. **Imputar variables con menos del 15% de nulos:**  
   Como las tres variables son categóricas, se imputan con la **moda** de cada una:
   - `Education_Level` -> Moda: `'Graduate'`
   - `Income_Category` -> Moda: `'Less than $40K'`
   - `Marital_Status` -> Moda: `'Married'`

In [8]:
# 1. Ver porcentaje de nulos por columna
porc_nulos = (df_nulos.isnull().sum() / len(df_nulos) * 100).round(2)
print("Porcentaje de nulos por columna:")
print(porc_nulos[porc_nulos > 0])

# 2. Eliminar registros con más del 15% de nulos (3 de 19 variables = 15.79%)
pred_cols = [c for c in df_nulos.columns if c != 'Attrition_Flag']
nulos_por_fila = (df_nulos[pred_cols].isnull().sum(axis=1) / len(pred_cols)) * 100
filas_a_borrar = (nulos_por_fila > 15.0).sum()
print(f"\nFilas eliminadas con > 15% de nulos: {filas_a_borrar}")

df_preparado = df_nulos.loc[nulos_por_fila <= 15.0].copy()

# 3. Imputar las columnas categóricas con su moda
for col in ['Education_Level', 'Income_Category', 'Marital_Status']:
    moda = df_preparado[col].mode()[0]
    df_preparado[col] = df_preparado[col].fillna(moda)
    print(f"- Imputada '{col}' con la moda: '{moda}'")

print(f"\nTotal de nulos restantes en el dataset: {df_preparado.isnull().sum().sum()}")
print(f"Dimensiones actuales: {df_preparado.shape[0]} filas y {df_preparado.shape[1]} columnas")

Porcentaje de nulos por columna:
Education_Level    15.00
Marital_Status      7.40
Income_Category    10.98
dtype: float64

Filas eliminadas con > 15% de nulos: 7
- Imputada 'Education_Level' con la moda: 'Graduate'
- Imputada 'Income_Category' con la moda: 'Less than $40K'
- Imputada 'Marital_Status' con la moda: 'Married'

Total de nulos restantes en el dataset: 0
Dimensiones actuales: 10120 filas y 20 columnas

In [9]:
# Cálculo exacto del porcentaje de nulos por columna (sin redondear) frente al umbral del 15%
for col in ['Education_Level', 'Income_Category', 'Marital_Status']:
    n_nulos = df_nulos[col].isnull().sum()
    pct_exacto = n_nulos / len(df_nulos) * 100
    print(f"{col}: {n_nulos} / {len(df_nulos)} = {pct_exacto:.4f}% -> supera el 15%: {pct_exacto > 15}")

Education_Level: 1519 / 10127 = 14.9995% -> supera el 15%: False
Income_Category: 1112 / 10127 = 10.9805% -> supera el 15%: False
Marital_Status: 749 / 10127 = 7.3961% -> supera el 15%: False

### 7. Análisis de correlaciones (Redundancia e Irrelevancia)
Calculamos la matriz de correlación de Pearson entre las variables numéricas para ver si hay redundancia (multicolinealidad).
- Notamos que `Credit_Limit` y `Avg_Open_To_Buy` tienen una correlación de **0.996** (casi 1.0). Esto pasa porque contablemente el cupo disponible es el cupo total menos el saldo rotativo. Por tanto, eliminamos `Avg_Open_To_Buy` por redundancia.
- Otras relaciones como `Customer_Age` y `Months_on_book` (0.79) o `Total_Trans_Amt` y `Total_Trans_Ct` (0.81) son moderadas y las conservamos.

In [10]:
# Matriz de correlación
plt.figure(figsize=(10, 8))
sns.heatmap(df_preparado.select_dtypes(include=[np.number]).corr(), annot=True, fmt=".2f", cmap="Blues")
plt.title("Matriz de Correlación entre Variables Numéricas", fontweight='bold')
plt.show()

# Eliminamos la variable redundante Avg_Open_To_Buy (corr = 0.996 con Credit_Limit)
df_final = df_preparado.drop(columns=['Avg_Open_To_Buy']).copy()
print(f"Dimensiones finales tras eliminar 'Avg_Open_To_Buy': {df_final.shape[0]} filas x {df_final.shape[1]} columnas")

Dimensiones finales tras eliminar 'Avg_Open_To_Buy': 10120 filas x 19 columnas

In [11]:
# Creamos una copia para el análisis de relevancia convirtiendo la variable objetivo a binaria
df_relevancia = df_final.copy()
df_relevancia['Attrition_Numeric'] = df_relevancia['Attrition_Flag'].apply(lambda x: 1 if x == 'Attrited Customer' else 0)

# Calculamos la correlación de las variables numéricas con la variable objetivo
correlaciones_relevancia = df_relevancia.select_dtypes(include=[np.number]).corr()['Attrition_Numeric'].drop('Attrition_Numeric')
correlaciones_relevancia = correlaciones_relevancia.sort_values(ascending=False)

# Graficamos la relevancia (correlación con Attrition_Flag)
plt.figure(figsize=(10, 6))
sns.barplot(x=correlaciones_relevancia.values, y=correlaciones_relevancia.index, palette='RdBu_r')
plt.axvline(x=0, color='black', linestyle='--', linewidth=1)
plt.title("Relevancia de Variables Numéricas con la Deserción (Attrition_Flag)", fontsize=14, fontweight='bold')
plt.xlabel("Coeficiente de Correlación de Pearson", fontsize=12)
plt.ylabel("Variables Numéricas", fontsize=12)
plt.tight_layout()
plt.show()

#### Conclusión de la relevancia de las variables numéricas
La gráfica muestra que las variables más relevantes son las del comportamiento transaccional. `Total_Trans_Ct` tiene la correlación más fuerte con la deserción (-0.37), seguida de `Total_Ct_Chng_Q4_Q1` (-0.29), `Total_Revolving_Bal` (-0.26), `Avg_Utilization_Ratio` (-0.18), `Total_Trans_Amt` (-0.17), `Total_Relationship_Count` (-0.15) y `Total_Amt_Chng_Q4_Q1` (-0.13), todas negativas, lo que indica que los clientes que usan menos la tarjeta y tienen menos productos con el banco son los que más abandonan. En sentido contrario, `Contacts_Count_12_mon` (0.20) y `Months_Inactive_12_mon` (0.15) se relacionan positivamente con el abandono, porque más contactos con el banco y más meses inactivos anticipan la salida del cliente.

Las menos relevantes son `Months_on_book` (0.01), `Customer_Age` (0.02), `Dependent_count` (0.02) y `Credit_Limit` (-0.02), con correlaciones prácticamente nulas. Aun así decidimos no eliminar ninguna, porque la correlación de Pearson solo mide relaciones lineales y estas variables pueden aportar en combinación con otras o con relaciones no lineales que sí capturan los árboles y los ensambles, y porque forman parte del conjunto de predictoras registrado. `Avg_Open_To_Buy` ya se había eliminado antes por redundancia y no por irrelevancia.

A continuación se evalúa la relevancia de las variables categóricas, que no entran en la correlación de Pearson, mediante la prueba de independencia chi cuadrado y la V de Cramér como medida del tamaño de la asociación.

In [12]:
# Relevancia de las variables categóricas frente a Attrition_Flag con chi-cuadrado y V de Cramér
cat_cols = ['Gender', 'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category']
filas_chi2 = []
for col in cat_cols:
    tabla = pd.crosstab(df_final[col], df_final['Attrition_Flag'])
    chi2, p_valor, gl, _ = stats.chi2_contingency(tabla)
    v_cramer = np.sqrt(chi2 / (tabla.values.sum() * (min(tabla.shape) - 1)))
    tasa = pd.crosstab(df_final[col], df_final['Attrition_Flag'], normalize='index')['Attrited Customer'] * 100
    filas_chi2.append({'Variable': col, 'Chi-cuadrado': round(chi2, 2), 'gl': gl,
                       'p-valor': round(p_valor, 4), 'V de Cramér': round(v_cramer, 4),
                       'Significativa (p < 0.05)': 'Sí' if p_valor < 0.05 else 'No',
                       'Tasa de abandono por categoría (%)': tasa.round(2).to_dict()})

tabla_chi2 = pd.DataFrame(filas_chi2).sort_values('V de Cramér', ascending=False).reset_index(drop=True)
tabla_chi2

,Variable,Chi-cuadrado,gl,p-valor,V de Cramér,Significativa (p < 0.05),Tasa de abandono por categoría (%)
0,Gender,13.90,1,0.0002,0.0371,Sí,"{'F': 17.36, 'M': 14.62}"
1,Income_Category,12.77,4,0.0125,0.0355,Sí,"{'$120K +': 17.33, '$40K - $60K': 15.14, '$60K - $80K': 13.48, '$80K - $120K': 15.77, 'Less than $40K': 17.1}"
2,Education_Level,11.26,5,0.0465,0.0334,Sí,"{'College': 15.2, 'Doctorate': 21.06, 'Graduate': 15.99, 'High School': 15.2, 'Post-Graduate': 17.83, 'Uneducated': 15.94}"
3,Marital_Status,3.94,2,0.1393,0.0197,No,"{'Divorced': 16.18, 'Married': 15.42, 'Single': 16.94}"
4,Card_Category,2.23,3,0.5251,0.0149,No,"{'Blue': 16.1, 'Gold': 18.1, 'Platinum': 25.0, 'Silver': 14.77}"

#### Interpretación y decisión para las variables categóricas
Con un nivel de significancia de 0.05, `Gender` (p = 0.0002), `Income_Category` (p = 0.012) y `Education_Level` (p = 0.046) muestran una asociación estadísticamente significativa con la deserción, mientras que `Marital_Status` (p = 0.139) y `Card_Category` (p = 0.525) no la muestran. Sin embargo, todos los valores de V de Cramér están por debajo de 0.04, lo que indica una asociación muy débil incluso en las significativas, ya que con más de 10 mil registros diferencias pequeñas en las tasas de abandono alcanzan a ser significativas. Por ejemplo, las mujeres abandonan en 17.4% frente al 14.6% de los hombres, y en `Card_Category` la tasa de Platinum es 25% pero con solo 20 clientes.

Concluimos que las variables categóricas aportan poca información por sí solas comparadas con las variables transaccionales. Aun así no eliminamos ninguna, porque forman parte del conjunto de 18 predictoras registrado, porque el chi cuadrado solo evalúa la relación de cada variable de forma aislada y no sus interacciones con las demás, y porque su costo dentro de los modelos es bajo. `Marital_Status` y `Card_Category` quedan identificadas como las candidatas más débiles, y su aporte real se revisará con la importancia de variables de los modelos en el notebook de modelado.

### 8. Exportación del dataset limpio
Guardamos los datos listos en `credit_card_churn_limpio.csv` (10,120 filas y 19 columnas) para utilizarlos directamente en el Notebook 02 de Modelado Predictivo.

In [13]:
# Guardamos el archivo depurado
df_final.to_csv("credit_card_churn_limpio.csv", index=False)
print("Archivo 'credit_card_churn_limpio.csv' guardado con éxito.")
print(f"Columnas resultantes ({len(df_final.columns)}): {list(df_final.columns)}")

Archivo 'credit_card_churn_limpio.csv' guardado con éxito.
Columnas resultantes (19): ['Attrition_Flag', 'Customer_Age', 'Gender', 'Dependent_count', 'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category', 'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon', 'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt', 'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio']